/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mymos_jwinapi_Jwinapi */

#ifndef _Included_com_mymos_jwinapi_Jwinapi
#define _Included_com_mymos_jwinapi_Jwinapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mymos_jwinapi_Jwinapi
 * Method:    setVolumeLevel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mymos_jwinapi_Jwinapi_setVolumeLevel
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mymos_jwinapi_Jwinapi
 * Method:    getVolumeLevel
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mymos_jwinapi_Jwinapi_getVolumeLevel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
